<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-35HBDVU" failures="1" tests="1" name="Default test(failed)" time="0.026" errors="0" timestamp="19 Jul 2025 08:12:53 GMT">
  <testcase classname="com.app.testng.Validation_One" name="test1" time="0.011">
    <failure type="java.lang.AssertionError" message="expected [Aiite] but found [Aiit]">
      <![CDATA[java.lang.AssertionError: expected [Aiite] but found [Aiit]
	at com.app.testng.Validation_One.test1(Validation_One.java:16)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="com.app.testng.Validation_One" name="test4" time="0.0">
    <ignored/>
  </testcase> <!-- test4 -->
  <testcase classname="com.app.testng.Validation_One" name="test3" time="0.0">
    <ignored/>
  </testcase> <!-- test3 -->
  <testcase classname="com.app.testng.Validation_One" name="test2" time="0.0">
    <ignored/>
  </testcase> <!-- test2 -->
</testsuite> <!-- Default test(failed) -->
